// <auto-generated />
namespace AIMH_Sialkot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change8));
        
        string IMigrationMetadata.Id
        {
            get { return "201601190851160_change8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
